### ISSUE TITLE
Scrum report (Due Jun 25 10PM)

### ISSUE THREAD

**Issue by sroyracha** [min2028/GuardNav#30]

**Comment by min2028** [comment]
Name: Aung Khant Min
CSID: d9p3n

What did you work on this past iteration?
During the past iteration, I setup MongoDB mongoose, perform data modelling and initialized it with the crime data. I also used react routers to route between pages in the client-side. 

What were any major issues/challenges you ran into?
The major challenge I ran into this iteration was connecting mongo atlas and local server since I did not realized the difference between cloud db and local db server as well as with the local host server.

What do you plan to work on for this coming iteration (2 weeks)?
For the coming iteration, I plan to work on the authentication with google OAuth on the server-side as well as creating new models for the data that will be stored with authentication such as username, history, etc.

**Comment by seiyoung-lee** [comment]
Name: Sei Young Andres Lee
CSID: r1m2b

What did you work on this past iteration?
I worked on the landing page. Basically working on the styling and the html on the front page of the app.

What were any major issues/challenges you ran into?
The major challenge I ran into was limiting the amount of coupling in each component and making the css look the way I wanted it to look. 

What do you plan to work on for this coming iteration (2 weeks)?
For the coming iteration, I plan to work on the authentication with google OAuth on the front-end.

**Comment by AayushRaghuvamshi** [comment]
Name: Aayush Raghuvamshi
CSID: v5x2b

What did you work on this past iteration?
During the past iteration, I obtained and cleaned the VPD crime dataset spannign 20 years of crime history, I then used that data to create a Heat Map Layer that I successfully got to render.

What were any major issues/challenges you ran into?
Documentation for google heatmap api is really bad, so debugging certain issues on my own like the google api constantly appearing as undefined was brutal. Currently the biggest issue is that because the dataset is so large, the heatmap layer rendering process creates massive latency issues when interacting with trip history/planning.

What do you plan to work on for this coming iteration (2 weeks)?
For the coming iteration, I plan to work on some kind of solution to help fix above mentioned latency issues, and I'll also work on route planning logic.

**Comment by kmdicksn** [comment]
Name: Dickson Ngan
CSID: l5x2b

What did you work on this past iteration (2 weeks)?
For the past iteration, I worked on designing and developing the route planning page and incorporating Google Map's Directions API to get the direction and route information. I also used Redux to store the history data with the ability to add a route from the route planning page and the ability to clear the entire history from the navigation bar.

What were any major issues/challenges you ran into?
I ran into a bug where the state was rerendering constantly and calling the Google Maps API hundreds of thousands of times. This caused the page to freeze and become unresponsive. Due to the lack of sufficient documentation of the library, it was also very hard to find out the reason why.

What do you plan to work on for this coming iteration (2 weeks)?
For the next iteration, I plan on continuing to work on the route history by adding the ability to favourite routes as well as working on adding history to the database.

**Comment by sroyracha** [comment]
Name: Ryosuke Urawa
CSID: c5w7t 

What did you work on this past iteration (2 weeks)?
For the past iteration, I worked on creating a landing page and update the figma design. Also created sub-folders to group all components we created as there were quite many components  under the same folder.

What were any major issues/challenges you ran into?
The major challenge was resolving all the merge conflicts as we initially missed to include some files/folders including node_modules.

What do you plan to work on for this coming iteration (2 weeks)?
For the next iteration, I plan on continuing to work on creating necessary pages/components for user preference, and allow users to save their favourite locations, and display them when the map page is rendered.
