### ISSUE TITLE
Scrum Report May 28th

### ISSUE THREAD

**Issue by kmdicksn** [min2028/GuardNav#4]

**Comment by seiyoung-lee** [comment]
Name: Andres Lee
CSID: r1m2b

During the past iteration, my focus was on defining the minimum requirements, standard requirements, and stretch requirements for our group's application, along with creating sketches of its interface. A major challenge we faced was assessing the feasibility of completing the application within the given summer timeframe. To address this, we conducted research to identify libraries and frameworks that could assist us and made adjustments to make the project more achievable. Additionally, by categorizing the most challenging tasks as stretch requirements, we modified the application to be a little simpler. In the upcoming iteration, my plan is to contribute by listing potential front-end components and implementing some of them in react/redux.

**Comment by min2028** [comment]
Name: Aung Khant Min
CSID: d9p3n

During the previous iteration, I took part in breaking down the project into requirements into MVP and non-MVP categories, as well as, sketching prototypes and setting up the repository.

The major challenge was coming up with the project idea itself and planning the requirements in a way such that they can be done in a set limited time. To alleviate this, we will base the project solely on the MVP requirements and will only add some of the non-MVP functionalities if time permits. 

In the coming iteration, I plan to work on the UI of the project by fleshing out the component structure of the app and focus on creating a component and styling it.

**Comment by kmdicksn** [comment]
Name: DIckson Ngan
CSID: l5x2b

**1. What did you work on this past iteration (2 weeks)?**
For the past iteration, I took part in the initial project idea creation, the ideation of minimum, standard, and stretch goals, sketching prototypes and initiating the frontend of the project. I've also experimented with various map APIs such as Mapbox and Google Maps to assess the best one for our situation.

**2. What were any major issues/challenges you ran into?**
The main challenge was assessing the feasibility of the requirements we have set within the limited timeframe of the project. This required assessing each requirement and deciding if it was important to the core use of the project while also weighing their difficulty.

**3. What do you plan to work on for this coming iteration (2 weeks)?**
For the coming iteration, I plan to help finish the high-fidelity prototypes of the project and start creating the components such as the map.

**Comment by AayushRaghuvamshi** [comment]
Name: Aayush Raghuvamshi
CSID: v5x2b

**1. What did you work on this past iteration (2 weeks)?**
- I helped develop our project idea and flesh out our project progress details as specified in Project Progress 1 and tried to bulletproof our high level idea by involving ideas such as keeping a disclaimer for using our app to ensure we hold no liability in a user's decision based on our app's suggestions, I also made the focus of our project to be user friendliness rather than technical sophistication. I also helped onboard our new member by explaining the whole project to him, since an old member of ours dropped the course.

**2. What were any major issues/challenges you ran into?**
- The biggest challenge we faced was deciding what should go in minimum, standard and stretch requirements. User profiles and authentication for instance has been in all 3 only to finally end up in stretch, fleshing our minimum requirement breakdown was also a bit challenging, but the most challenging of all was communicating ideas efficiently enough to ensure we were all on the same page.

**3. What do you plan to work on for this coming iteration (2 weeks)?**
- I will be working on fleshing out the structure of our project, and developing components such as the navbar and a trip form.

**Comment by sroyracha** [comment]
Name: Ryosuke Urawa
CSID: c5w7t

1. What did you work on this past iteration (2 weeks)?
Since I joined the team late, I spend this past iteration on catching up to the team. I also hosted a meeting to review our project requirement, created a slack channel to post pull requests, and added detailed spec and design on figma.

2. What were any major issues/challenges you ran into?
The main challenge was understanding the project goal and redesigning what should be the minimal requirement. Since some minimal requirement was related to the stretched requirement,  reviewing the project and reevaluating how we meet the requirement required some time to discuss with other members.

3. What do you plan to work on for this coming iteration (2 weeks)?
For the coming iteration, I plan to start creating some of the react components and stay aligned to the team to catch potential blockers or issues.
