### ISSUE TITLE
Scrum report (Due Jul 16 10PM)

### ISSUE THREAD

**Issue by min2028** [min2028/GuardNav#45]

**Comment by min2028** [comment]
Name: Aung Khant Min
CSID: d9p3n

What did you work on this past iteration?
During the past iteration, I performed data modelling for users and work on the authentication with google OAuth. I also created history apis in the server-side and also made some UI changes to the client-side Navbar. 

What were any major issues/challenges you ran into?
Having not worked on authentication before, it took time to understand the processes. I followed the documentations, only to realize later that there is a library for Google OAuth in react which sets everything up. But, I learned a lot from following the documentations.

What do you plan to work on for this coming iteration (2 weeks)?
In the coming iteration, I plan to work on making the logged in user persist across the app using refresh tokens and also create a logout functionality for the users.

**Comment by kmdicksn** [comment]
Name: Dickson Ngan
CSID: l5x2b

**What did you work on this past iteration?**
For this past iteration, I mostly worked on creating an expanded history to allow the user to view the entire trip history in a scrollable container as well as enabling favouriting/saving trips. To do so, I worked with Min to create the necessary endpoints on the server and integrating them within the frontend by creating the http requests using axios. I also did some bug fixes and general UI improvements to the map page.

**What were any major issues/challenges you ran into?**
I ran into a lot of trouble integrating the backend and the frontend for the history as I was unfamiliar with the fact that the MongoDB requires a 24 character long ID and not a UUID. This meant the history I was creating were not getting returned to the frontend. This was fixed with the help of Min and I was able to get it working in the end.

**What do you plan to work on for this coming iteration (2 weeks)?**
In the next coming iteration, I plan on continuing to polish the frontend of the map page, integrating the user profile page into the map page, as well as potentially helping with the eventual deployment of the application.

**Comment by AayushRaghuvamshi** [comment]
Name: Aayush Raghuvamshi
CSID: v5x2b

What did you work on this past iteration?
During the past iteration, I set up Route planning, which involved cleaning and processing our dataset to make it more usable, truncating it from 90 MB to 2.56 MB, figuring out what options the google maps api allows for route customization, figuring out the math for route planning given the very limited functionality that the api allows, and putting it all together in code.

What were any major issues/challenges you ran into?
The api gives you literally no control over route planning. I had to go through a whole paradigm shift in my approach. I had to move away from the thought process of giving the api points to avoid, to giving it enough points to plan a route with, which google allows only 23 of. This late into the project we have realized that using google maps for our idea was a mistake, something like Mapbox would have been way better given its flexible customizability.

What do you plan to work on for this coming iteration (2 weeks)?
Clean up our route planning logic to whatever extent possible, implementing some kind of a border system to make sure the origin and destination provided by the user are within the bounds of the crime dataset, and making our databse integration more bug free in any way I can.

**Comment by seiyoung-lee** [comment]
Name: Sei Young Andres Lee
CSID: r1m2b

What did you work on this past iteration?
For this past iteration I worked on integrating the frontend of authenticating a user and creating a schema for the history model. This history model is hooked to one user.

What were any major issues/challenges you ran into?
I ran into trouble trying to create a custom type for the schema of the history model.

What do you plan to work on for this coming iteration (2 weeks)?
In the next coming iteration, I plan on continuing to polish the frontend of the authentication of google and working more on the backend.

**Comment by sroyracha** [comment]
Name: Ryosuke Urawa
CSID: c5w7t 

What did you work on this past iteration?
For this past iteration I worked on defining what to go in for the user preference; implemented user preference page; and implemented logic to save user's favourite location.

What were any major issues/challenges you ran into?
I faced couple issues with configuring google auth and db but the team members supported me to set them up, and provided solution to resolve errors I had locally.

What do you plan to work on for this coming iteration (2 weeks)?
In the next coming iteration, I plan on displaying user's saved locations in the map page, and sync up with other members to go over what other thing should go in the user preference page.
