### ISSUE TITLE
Scrum report (Due Jul 30 10PM)

### ISSUE THREAD

**Issue by min2028** [min2028/GuardNav#56]

**Comment by min2028** [comment]
Name: Aung Khant Min
CSID: d9p3n

What did you work on this past iteration?
During the past iteration, I continued my work on the authentication with google OAuth to make sure user login persist through page refreshes and access token expiration.

What were any major issues/challenges you ran into?
Understanding the concepts and workflow of Google OAuth is quite complicated but integrating it into the app is much harder. I have finished the token request handler between the server and google server but implementing the workflow of handling the access token expiry between server and client is extremely hard.

What do you plan to work on for this coming iteration (2 weeks)?
In the coming iteration, I plan to continue my work on authentication by using Auth0 SDK instead of handling the token refreshes and server-client Auth workflow manually.

**Comment by seiyoung-lee** [comment]
Name: Sei Young Andres Lee
CSID: r1m2b

What did you work on this past iteration?
I worked on deploying the application and fixing some bugs on the user authentication.

What were any major issues/challenges you ran into?
The only problem I ran into was understanding why the loading of the user created a weird tree of the previous global state. I was able to fix it by changing how global state was stored.

What do you plan to work on for this coming iteration (2 weeks)?
In the coming iteration, I plan to work on fixing some bugs, changing the requirements on the webapp, and contributing on wherever else needs more help.

**Comment by kmdicksn** [comment]
Name: Dickson Ngan
CSID: l5x2b

**What did you work on this past iteration?**
For the past iteration, I mainly worked on bug fixes within the map page as well as incorporating the profile login and logout system to the map page.

**What were any major issues/challenges you ran into?**
Ensuring that everything works properly required a lot of manual testing within the UI. As well, isolating the bugs such as the history card not properly storing information and being unclickable was tedious.

**What do you plan to work on for this coming iteration (2 weeks)?**
As the application will be primarily a desktop application at the moment, I plan to add the feature to send directions to the user's phone via SMS so that it will be easy for the user to bring the directions with them on the go. I also plan to incorporate the saved destinations feature from the profile page to the map page. Finally, I will do some finally polishing and bug fixes for the upcoming final presentation.

**Comment by AayushRaghuvamshi** [comment]
Name: Aayush Raghuvamshi
CSID: v5x2b

What did you work on this past iteration?
For the past iteration, I revamped the entire route planning logic, making it look much cleaner and mire efficient. I also added routing to tabs in the route options to change risk level of each route.

What were any major issues/challenges you ran into?
Nothing was too hard this time.

What do you plan to work on for this coming iteration (2 weeks)?
We are making a list of bugs we currently have, I as well as the others will be going bug bounty hunting to make the app as bug free as possible. I finished all my main responsibilities for the project, so I'll just be refining route planning while also helping whoever in my team can use help.

**Comment by sroyracha** [comment]
Name: Ryosuke Urawa
CSID: c5w7t

What did you work on this past iteration?
For the past iteration, I worked on implementing the saving the favourite locations and allow user to use short cut in map page. 

What were any major issues/challenges you ran into?
Figuring out that I couldn't use uuid as in `new Types.ObjectId(model._id)` where _id uses uuid. Thanks to @kmdicksn 's comment, I could get over it, but spent too much time on this issue.

What do you plan to work on for this coming iteration (2 weeks)?
Before merging in my changes, there are some fixes to be merged in, so will validate my commit after those are in.
